spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/aywin/islack-config
        monitor:
          github: enabled

server:
  port: 8888

management:
  security:
    enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: '*'
