server:
  port: 8003
spring:
  datasource:
    url: jdbc:sqlserver://islack.database.windows.net:1433;database=profile
    username: islack
    password: iDBrahim1
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true