apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth-deploy
  labels:
    app: oauth
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oauth
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - image: islackregistry.azurecr.io/islack/oauth:latest
          name: oauth
          imagePullPolicy: "Always"
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: my-secret
